version: "3.9"

services:

  backend:
    build: ./backend
    command: >
      daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: react
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: ./backend
    command: celery -A backend worker --pool=solo -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis
      - postgres

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis
      - postgres

volumes:
  postgres_data:
