# Generated by Django 6.0.2 on 2026-08-04 17:29

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyverificationdocument',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='agency.agency'),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='included',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='excluded',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='departure',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='tourview',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_views', to='agency.tour'),
        ),
        migrations.AddField(
            model_name='tourview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['country'], name='country_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['city'], name='city_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['country'], name='agency_tour_country_b6421d_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['city'], name='agency_tour_city_eebef6_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['category'], name='agency_tour_categor_9e7d13_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['flight_included'], name='agency_tour_flight__e60488_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['price'], name='agency_hote_price_190fee_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['stars'], name='agency_hote_stars_b800e2_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['meal_plan'], name='agency_hote_meal_pl_205e61_idx'),
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['departure_date'], name='agency_depa_departu_6eeeb6_idx'),
        ),
    ]
