# Generated by Django 6.0.2 on 2026-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_tour_car_tour_flight_included_tour_guide_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='from_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='from_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
