# Generated by Django 6.0.2 on 2026-07-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_tour_from_city_tour_from_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='night',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
