# Generated by Django 6.0.2 on 2026-07-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_tour_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='night',
            new_name='nights',
        ),
    ]
