# Generated by Django 6.0.2 on 2026-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_tour_options_tour_country_trgm_tour_city_trgm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['price'], name='agency_depa_price_f2e070_idx'),
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['departure_date'], name='agency_depa_departu_6eeeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['stars'], name='agency_hote_stars_b800e2_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['meal_plan'], name='agency_hote_meal_pl_205e61_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['country'], name='agency_tour_country_b6421d_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['city'], name='agency_tour_city_eebef6_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['category'], name='agency_tour_categor_9e7d13_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['flight_included'], name='agency_tour_flight__e60488_idx'),
        ),
    ]
