# Generated by Django 6.0.2 on 2026-07-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='meal_plan',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast Only'), ('half_board', 'Half Board'), ('full_board', 'Full Board'), ('all_inclusive', 'All Inclusive')], max_length=50, null=True),
        ),
    ]
