# Generated by Django 6.0.2 on 2026-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_hotel_meal_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
