# Generated by Django 6.0.2 on 2026-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_tourview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
