# Generated by Django 6.0.2 on 2026-07-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_hotel_hotel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_price',
            new_name='price',
        ),
    ]
