# Generated by Django 6.0.2 on 2026-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_rename_hotel_price_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
