# Generated by Django 6.0.2 on 2026-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_departure_departure_time_departure_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='departure',
            name='agency_depa_price_f2e070_idx',
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['price'], name='agency_hote_price_190fee_idx'),
        ),
        migrations.RemoveField(
            model_name='departure',
            name='price',
        ),
    ]
