# Generated by Django 6.0.2 on 2026-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_remove_departure_agency_depa_price_f2e070_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='en', max_length=2),
        ),
    ]
