# Generated by Django 6.0.2 on 2026-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_tour_source_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
