# Generated by Django 6.0.2 on 2026-07-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_agency_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='total_seats',
        ),
    ]
