# Generated by Django 6.0.2 on 2026-07-31 16:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_alter_agency_owner'),
    ]

    operations = [
        TrigramExtension(),
    ]
