# Generated by Django 6.0.2 on 2026-08-03 19:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['country'], name='country_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['city'], name='city_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
