# Generated by Django 6.0.2 on 2026-08-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=2)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('excluded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='agency.excluded')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('excluded', 'language')},
            },
        ),
        migrations.CreateModel(
            name='IncludedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=2)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('included', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='agency.included')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('included', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TourTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=2)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='agency.tour')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('tour', 'language')},
            },
        ),
    ]
