# Generated by Django 6.0.2 on 2026-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourtranslation',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tourtranslation',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
