# Generated by Django 6.0.2 on 2026-07-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_tourtranslation_city_tourtranslation_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itinerarytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itinerarytranslation',
            name='itinerary',
        ),
        migrations.DeleteModel(
            name='HotelTranslation',
        ),
        migrations.DeleteModel(
            name='ItineraryTranslation',
        ),
    ]
