# Generated by Django 6.0.2 on 2026-07-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
