# Generated by Django 6.0.2 on 2026-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='google_id',
        ),
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
